### ISSUE TITLE
Consider using Notion API

### ISSUE THREAD

**Issue by oswinrodrigues** [oswinrodrigues/steward-little#10]
To add a database item, one purchase at a time, rather than manually importing a CSV at the end.

Is this valuable? Even if we're already generating monthly CSVs in the process? Should we then not bother with these CSVs?

**Comment by eerodrigues** [comment]
Resolved in 21d1e929a30c825ffca5849a6bf27f39e4a82205. 

I experimented with bypassing the categorized CSV and going straight from categorization to Notion, but it was super slow to import (> 5 min for one month of data, and even then it failed partway through). So, keeping the CSVs seemed to be a better choice with respect to both performance and safety. Until we have a solution for checking against duplicate entries, partial uploads are a big issue.
